cicse:
  # Absolute URL to the CI-CSE homepage
  url: "https://ci-cse.github.io"
  # How the CI-CSE page is referred to in the top bar
  title: "CI-CSE"
  # Show the link to CI-CSE homepage in the top bar?
  bar_link: true
  # Array of nav links for the top bar
  # Each item should be an object with keys:
  # * link - local path. It will be passed to the `relative_url` filter
  # * title - text of the link
  nav_links: []


tailwindcss:
  config: 'gem:jekyll-theme-cicse/tailwind.config.js'

gem_resolver:
  transform:
    - tailwind.config
